-- Progression Tracker M3: sessions & attendance.
-- A halaqah carries an optional weekly recurrence rule (halaqah.schedule jsonb,
-- already present from M1). Sessions are materialized rows; recurring ones are
-- generated by the app over a rolling horizon, ad-hoc ones added by the teacher.
-- Attendance is one row per (session, student membership).

-- ---------------------------------------------------------------------------
-- session
-- ---------------------------------------------------------------------------
create table public.session (
  id uuid primary key default gen_random_uuid(),
  halaqah_id uuid not null references public.halaqah(id) on delete cascade,
  scheduled_at timestamptz not null,
  is_adhoc boolean not null default false,
  canceled boolean not null default false,
  created_at timestamptz not null default now(),
  -- One recurring session per halaqah per time slot; ad-hoc may duplicate a slot
  -- but the app dedupes generated ones against this.
  unique (halaqah_id, scheduled_at)
);

alter table public.session enable row level security;

create index session_halaqah_idx on public.session (halaqah_id);
create index session_scheduled_idx on public.session (scheduled_at);

-- ---------------------------------------------------------------------------
-- attendance
-- ---------------------------------------------------------------------------
create table public.attendance (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.session(id) on delete cascade,
  membership_id uuid not null references public.membership(id) on delete cascade,
  -- present | absent | late | excused.
  status text not null default 'present'
    check (status in ('present', 'absent', 'late', 'excused')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, membership_id)
);

alter table public.attendance enable row level security;

create index attendance_session_idx on public.attendance (session_id);
create index attendance_membership_idx on public.attendance (membership_id);

-- ---------------------------------------------------------------------------
-- Security-definer helpers — resolve session -> halaqah teacher / member
-- without recursing through session RLS.
-- ---------------------------------------------------------------------------
create or replace function public.teaches_session(_session uuid)
  returns boolean
  language sql
  security definer
  stable
  set search_path = public
as $$
  select exists (
    select 1 from public.session s
    join public.halaqah h on h.id = s.halaqah_id
    where s.id = _session and h.teacher_id = auth.uid()
  );
$$;

create or replace function public.member_of_session(_session uuid)
  returns boolean
  language sql
  security definer
  stable
  set search_path = public
as $$
  select exists (
    select 1 from public.session s
    join public.membership m on m.halaqah_id = s.halaqah_id
    where s.id = _session
      and m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

-- ---------------------------------------------------------------------------
-- session RLS
-- ---------------------------------------------------------------------------
-- Teacher manages sessions in their halaqat.
create policy "Teacher manages halaqah sessions"
  on public.session for all
  using (public.is_halaqah_teacher(halaqah_id))
  with check (public.is_halaqah_teacher(halaqah_id));

-- Active members read sessions of their halaqat.
create policy "Members read halaqah sessions"
  on public.session for select
  using (public.is_active_member(halaqah_id));

-- ---------------------------------------------------------------------------
-- attendance RLS
-- ---------------------------------------------------------------------------
-- Teacher manages attendance for sessions in their halaqat.
create policy "Teacher manages session attendance"
  on public.attendance for all
  using (public.teaches_session(session_id))
  with check (public.teaches_session(session_id));

-- Student reads own attendance rows.
create policy "Student reads own attendance"
  on public.attendance for select
  using (public.owns_membership(membership_id));
